h2.implicitRelativePath: true

spring.output.ansi.enabled: ALWAYS

spring:
  datasource.url: jdbc:hsqldb:file:~/desktop/craftdb/craft.db
  jpa:
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql:true